    window.database = [
      { n:"AAS", syn:["AAS","Acido acetilsalicilico","Aspirina"], d:100, unit:"mg", mv:"30 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT" },
      { n:"Acebutolol", syn:["Acebutolol"], d:25, unit:"mg", mv:"10 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Aceclofenaco", syn:["Aceclofenaco"], d:15, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Acemetacina", syn:["Acemetacina"], d:8.5, unit:"mg", mv:"11 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Aciclovir", syn:["Aciclovir"], d:300, unit:"mg", mv:"3 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Acido Nalidixico", syn:["Acido Nalidixico","Ácido Nalidíxico"], d:150, unit:"mg", mv:"7 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Acido Tiaprofenico", syn:["Acido Tiaprofenico","Ácido Tiaprofênico"], d:40, unit:"mg", mv:"2 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Acido Valproico", syn:["Acido Valproico","Ácido Valpróico","Depakene"], d:200, unit:"mg", mv:"20 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Alprazolam", syn:["Alprazolam","Frontal"], d:0.05, unit:"mg", mv:"15 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil (se depressão respiratória grave)", support:"Observar depressão SNC. Meia-vida longa.", ref:"AACT/EAPCCT" },
      { n:"Amilorida", syn:["Amilorida"], d:1.5, unit:"mg", mv:"9 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Amitriptilina", syn:["Amitriptilina"], d:3, unit:"mg", mv:"25 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Amlodipina", syn:["Amlodipina"], d:0.2, unit:"mg", mv:"50 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Amobarbital", syn:["Amobarbital"], d:4, unit:"mg", mv:"25 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Amoxicilina", syn:["Amoxicilina"], d:250, unit:"mg", mv:"1.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Ampicilina", syn:["Ampicilina"], d:550, unit:"mg", mv:"1.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Atenolol", syn:["Atenolol"], d:5, unit:"mg", mv:"7 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Avanafil", syn:["Avanafil"], d:6, unit:"mg", mv:"17 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Azapropazona", syn:["Azapropazona"], d:50, unit:"mg", mv:"14 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Azilsartana", syn:["Azilsartana"], d:5, unit:"mg", mv:"11 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Azitromicina", syn:["Azitromicina"], d:20, unit:"mg", mv:"4 dias", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Bambuterol", syn:["Bambuterol"], d:1.5, unit:"mg", mv:"21 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Barbital", syn:["Barbital"], d:20, unit:"mg", mv:"48 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Benazepril", syn:["Benazepril"], d:0.5, unit:"mg", mv:"22 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Bendroflumetiazida", syn:["Bendroflumetiazida"], d:0.4, unit:"mg", mv:"8.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Betaxolol", syn:["Betaxolol"], d:1, unit:"mg", mv:"22 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Bisoprolol", syn:["Bisoprolol"], d:0.7, unit:"mg", mv:"12 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Bromazepam", syn:["Bromazepam"], d:0.7, unit:"mg", mv:"20 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil (se depressão respiratória grave)", ref:"AACT/EAPCCT" },
      { n:"Bronfenaco", syn:["Bronfenaco"], d:10, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Bronfeniramina", syn:["Bronfeniramina"], d:3.5, unit:"mg", mv:"25 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Bumetanida", syn:["Bumetanida"], d:0.1, unit:"mg", mv:"3 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Buprenorfina", syn:["Buprenorfina"], d:0.01, unit:"mg", mv:"7 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona (0.4-2mg IV)", support:"Risco de depressão respiratória.", ref:"AACT/EAPCCT" },
      { n:"Butobarbital", syn:["Butobarbital"], d:6, unit:"mg", mv:"42 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Candesartana", syn:["Candesartana"], d:0.6, unit:"mg", mv:"9 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Captopril", syn:["Captopril"], d:3.5, unit:"mg", mv:"2 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Carbamazepina", syn:["Carbamazepina"], d:20, unit:"mg", mv:"20 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Carbonato Litio", syn:["Carbonato Litio","Lítio"], d:50, unit:"mg", mv:"24 hs", ca:"NÃO", lg:"Sim (RX)", noCharcoal:true, ref:"AACT/EAPCCT" },
      { n:"Carprofeno", syn:["Carprofeno"], d:20, unit:"mg", mv:"27 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Carteolol", syn:["Carteolol"], d:0.7, unit:"mg", mv:"12 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Carvedilol", syn:["Carvedilol"], d:2.5, unit:"mg", mv:"6 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Celiprolol", syn:["Celiprolol"], d:14, unit:"mg", mv:"6 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Cetobemidona", syn:["Cetobemidona"], d:0.4, unit:"mg", mv:"2.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Cetoprofeno", syn:["Cetoprofeno"], d:10, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Cetorolaco", syn:["Cetorolaco"], d:2, unit:"mg", mv:"5.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Cetotifeno", syn:["Cetotifeno"], d:0.3, unit:"mg", mv:"21 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Ciclizina", syn:["Ciclizina"], d:5, unit:"mg", mv:"20 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Ciclobarbital", syn:["Ciclobarbital"], d:8, unit:"mg", mv:"12 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Cilazapril", syn:["Cilazapril"], d:0.2, unit:"mg", mv:"9 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Cinarizina", syn:["Cinarizina"], d:12, unit:"mg", mv:"6 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Ciprofloxacino", syn:["Ciprofloxacino"], d:70, unit:"mg", mv:"5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Ciproheptadina", syn:["Ciproheptadina"], d:2, unit:"mg", mv:"9 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Citalopram", syn:["Citalopram"], d:2, unit:"mg", mv:"36 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Claritromicina", syn:["Claritromicina"], d:70, unit:"mg", mv:"5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Clemastina", syn:["Clemastina"], d:0.3, unit:"mg", mv:"21 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Cliclobenzaprina", syn:["Cliclobenzaprina"], d:1.5, unit:"mg", mv:"32 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Clobazam", syn:["Clobazam"], d:1.5, unit:"mg", mv:"79 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil (se necessário)", ref:"AACT/EAPCCT" },
      { n:"Clomipramina", syn:["Clomipramina"], d:4, unit:"mg", mv:"36 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Clonazepam", syn:["Clonazepam","Rivotril"], d:0.6, unit:"mg", mv:"40 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil (se necessário)", ref:"AACT/EAPCCT" },
      { n:"Clonidina", syn:["Clonidina"], d:0.01, unit:"mg", mv:"24 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Clopamida", syn:["Clopamida"], d:1.4, unit:"mg", mv:"10 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Clordiazepoxido", syn:["Clordiazepoxido"], d:2, unit:"mg", mv:"78 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil (se necessário)", ref:"AACT/EAPCCT" },
      { n:"Clorfeniramina", syn:["Clorfeniramina"], d:0.85, unit:"mg", mv:"43 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Clorpromazina", syn:["Clorpromazina"], d:6, unit:"mg", mv:"40 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Clorprotixeno", syn:["Clorprotixeno"], d:6, unit:"mg", mv:"12 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Dapoxetina", syn:["Dapoxetina"], d:4, unit:"mg", mv:"19 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Dapsona", syn:["Dapsona"], d:5, unit:"mg", mv:"30 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Desipramina", syn:["Desipramina"], d:3, unit:"mg", mv:"27 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Desvenlafaxina", syn:["Desvenlafaxina"], d:3, unit:"mg", mv:"15 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Dexcetoprofeno", syn:["Dexcetoprofeno"], d:5, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Dexibuprofeno", syn:["Dexibuprofeno"], d:60, unit:"mg", mv:"3.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Diazepam", syn:["Diazepam","Valium"], d:0.7, unit:"mg", mv:"48 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil (se necessário)", ref:"AACT/EAPCCT" },
      { n:"Diclofenaco", syn:["Diclofenaco","Cataflam","Voltaren"], d:7, unit:"mg", mv:"2 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Difenidramina", syn:["Difenidramina"], d:7.5, unit:"mg", mv:"9.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Diflunisal", syn:["Diflunisal"], d:50, unit:"mg", mv:"12 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Digoxina", syn:["Digoxina"], d:20, unit:"mcg", mv:"40 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Ac Anti-Digoxina (Fab)", ref:"AACT/EAPCCT" },
      { n:"Dihidrocodeina", syn:["Dihidrocodeina"], d:0.4, unit:"mg", mv:"3.5 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona", ref:"AACT/EAPCCT" },
      { n:"Diltiazem", syn:["Diltiazem"], d:5, unit:"mg", mv:"48 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Dipipanona", syn:["Dipipanona"], d:1.5, unit:"mg", mv:"3.5 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona", ref:"AACT/EAPCCT" },
      { n:"Dipirona", syn:["Dipirona","Novalgina"], d:100, unit:"mg", mv:"Update", ca:"Sim (< 1h)", lg:"Não", ref:"Bula" },
      { n:"Disopiramida", syn:["Disopiramida"], d:15, unit:"mg", mv:"11 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Doxepina", syn:["Doxepina"], d:4, unit:"mg", mv:"80 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Doxilamina", syn:["Doxilamina"], d:5, unit:"mg", mv:"10 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Duloxetina", syn:["Duloxetina"], d:5, unit:"mg", mv:"18 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Enalapril", syn:["Enalapril"], d:0.7, unit:"mg", mv:"11 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Eplerenona", syn:["Eplerenona"], d:7, unit:"mg", mv:"5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Eprosartana", syn:["Eprosartana"], d:40, unit:"mg", mv:"9 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Eritromicina", syn:["Eritromicina"], d:70, unit:"mg", mv:"2 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Escitalopram", syn:["Escitalopram"], d:1, unit:"mg", mv:"33 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Eslicarbazepina", syn:["Eslicarbazepina"], d:30, unit:"mg", mv:"20 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Espironolactona", syn:["Espironolactona"], d:10, unit:"mg", mv:"11.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Estazolam", syn:["Estazolam"], d:0.2, unit:"mg", mv:"24 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Etizolam", syn:["Etizolam"], d:0.1, unit:"mg", mv:"8 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Etodolaco", syn:["Etodolaco"], d:30, unit:"mg", mv:"7 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Famciclovir", syn:["Famciclovir"], d:50, unit:"mg", mv:"2 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Felodipina", syn:["Felodipina"], d:0.2, unit:"mg", mv:"25 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Fenbufeno", syn:["Fenbufeno"], d:40, unit:"mg", mv:"17 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Fenilefrina", syn:["Fenilefrina"], d:1, unit:"mg", mv:"3 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Feniramina", syn:["Feniramina"], d:3.5, unit:"mg", mv:"19 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Fenitoina", syn:["Fenitoina","Fenitoína"], d:20, unit:"mg", mv:"230 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Fenobarbital", syn:["Fenobarbital","Gardenal"], d:4, unit:"mg", mv:"5 dias", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Fenoprofeno", syn:["Fenoprofeno"], d:85, unit:"mg", mv:"3 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Fentanil", syn:["Fentanil"], d:0.04, unit:"mg", mv:"8 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona (0.4-2mg IV)", support:"Opióide potente. Risco de tórax rígido.", ref:"AACT/EAPCCT" },
      { n:"Ferro", syn:["Ferro","Sulfato Ferroso"], d:20, unit:"mg", mv:"6 hs", ca:"NÃO", lg:"Sim (RX)", noCharcoal:true, ref:"AACT/EAPCCT" },
      { n:"Flunitrazepam", syn:["Flunitrazepam","Rohypnol"], d:0.05, unit:"mg", mv:"35 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Fluoxetina", syn:["Fluoxetina","Prozac"], d:3, unit:"mg", mv:"16 dias", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Flurazepam", syn:["Flurazepam"], d:2, unit:"mg", mv:"5 dias", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Flurbiprofeno", syn:["Flurbiprofeno"], d:85, unit:"mg", mv:"6 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Fluvoxamina", syn:["Fluvoxamina"], d:15, unit:"mg", mv:"22 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Formoterol", syn:["Formoterol"], d:1.5, unit:"mcg", mv:"10 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Fosinopril", syn:["Fosinopril"], d:1, unit:"mg", mv:"11.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Furosemida", syn:["Furosemida","Lasix"], d:3, unit:"mg", mv:"Update", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Clortalidona", syn:["Clortalidona"], d:3.5, unit:"mg", mv:"50 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Clozapina", syn:["Clozapina"], d:10, unit:"mg", mv:"12 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Codeina", syn:["Codeina","Codeína"], d:2.5, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona (0.4-2mg IV)", support:"Opióide fraco. Risco de depressão resp.", ref:"AACT/EAPCCT" },
      { n:"Glibenclamida", syn:["Glibenclamida"], d:0.2, unit:"mg", mv:"Update", ca:"Sim (< 1h)", lg:"Não", support:"Monitorar hipoglicemia grave e prolongada.", ref:"AACT/EAPCCT" },
      { n:"Gliclazida", syn:["Gliclazida"], d:1.3, unit:"mg", mv:"12-20 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Glimepirida", syn:["Glimepirida"], d:0.04, unit:"mg", mv:"8 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Glipizida", syn:["Glipizida"], d:0.2, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Guanfacina", syn:["Guanfacina"], d:0.15, unit:"mg", mv:"18 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Haloperidol", syn:["Haloperidol","Haldol"], d:0.5, unit:"mg", mv:"Update", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Hidroclorotiazida", syn:["Hidroclorotiazida","HCTZ"], d:3.5, unit:"mg", mv:"15 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Hidromorfona", syn:["Hidromorfona"], d:0.1, unit:"mg", mv:"2.5 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona", ref:"AACT/EAPCCT" },
      { n:"Hidroxizine", syn:["Hidroxizine","Hidroxizina"], d:10, unit:"mg", mv:"20 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Ibuprofeno", syn:["Ibuprofeno","Alivium"], d:100, unit:"mg", mv:"2.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Imepitoin", syn:["Imepitoin"], d:30, unit:"mg", mv:"20 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Imidapril", syn:["Imidapril"], d:0.7, unit:"mg", mv:"24 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Imipramina", syn:["Imipramina","Tofranil"], d:4, unit:"mg", mv:"19 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Indacaterol", syn:["Indacaterol"], d:10, unit:"mcg", mv:"5 dias", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Indapamida", syn:["Indapamida"], d:0.4, unit:"mg", mv:"24 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Indometacina", syn:["Indometacina"], d:7, unit:"mg", mv:"11 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Irbesartana", syn:["Irbesartana"], d:10, unit:"mg", mv:"15 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Lacidipina", syn:["Lacidipina"], d:0.15, unit:"mg", mv:"19 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Lenalidomida", syn:["Lenalidomida"], d:0.7, unit:"mg", mv:"5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Lercanidipina", syn:["Lercanidipina"], d:0.4, unit:"mg", mv:"10 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Levobunolol", syn:["Levobunolol"], d:1, unit:"mg", mv:"7 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Levofloxacino", syn:["Levofloxacino"], d:35, unit:"mg", mv:"8 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Levomepromazina", syn:["Levomepromazina","Neozine"], d:6, unit:"mg", mv:"78 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Levotiroxina", syn:["Levotiroxina","Puran","Euthyrox"], d:20, unit:"mcg", mv:"7 dias", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Lidocaina", syn:["Lidocaina","Lidocaína"], d:5, unit:"mg", mv:"1.5 hs", ca:"Sim (< 1h)", lg:"Não", support:"Risco de convulsão e arritmia.", ref:"AACT" },
      { n:"Lisinopril", syn:["Lisinopril"], d:0.7, unit:"mg", mv:"12.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Litio", syn:["Litio","Lítio","Carbolitium"], d:50, unit:"mg", mv:"24 hs", ca:"NÃO", lg:"Não", noCharcoal:true, ref:"AACT/EAPCCT" },
      { n:"Lofepramina", syn:["Lofepramina"], d:4.5, unit:"mg", mv:"24 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Loprazolam", syn:["Loprazolam"], d:0.07, unit:"mg", mv:"14 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Lorazepam", syn:["Lorazepam"], d:2, unit:"mg", mv:"20 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Lormetazepam", syn:["Lormetazepam"], d:0.07, unit:"mg", mv:"11 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Lornoxicam", syn:["Lornoxicam"], d:0.8, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Losartana", syn:["Losartana"], d:3.5, unit:"mg", mv:"9 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Maprotilina", syn:["Maprotilina"], d:3, unit:"mg", mv:"90 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Meclozina", syn:["Meclozina"], d:5, unit:"mg", mv:"6 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Meloxicam", syn:["Meloxicam"], d:1, unit:"mg", mv:"20 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Meptazinol", syn:["Meptazinol"], d:8.5, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Metadona", syn:["Metadona","Mytedon"], d:0.4, unit:"mg", mv:"60 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona (0.4-2mg IV)", support:"Meia-vida muito longa. Naloxona repetida pode ser necessária.", ref:"AACT/EAPCCT" },
      { n:"Metformina", syn:["Metformina","Glifage"], d:80, unit:"mg", mv:"6.5 hs", ca:"Sim (< 1h)", lg:"Não", support:"Risco de acidose lática.", ref:"AACT/EAPCCT" },
      { n:"Metildopa", syn:["Metildopa"], d:15, unit:"mg", mv:"Update", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Metilfenidato", syn:["Metilfenidato","Ritalina"], d:1, unit:"mg", mv:"2 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Metolazona", syn:["Metolazona"], d:0.7, unit:"mg", mv:"10 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Metoprolol", syn:["Metoprolol","Selozok"], d:10, unit:"mg", mv:"3.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Midazolam", syn:["Midazolam","Dormonid"], d:1.0, unit:"mg", mv:"2.5 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil (se necessário)", ref:"AACT/EAPCCT" },
      { n:"Misoprostol", syn:["Misoprostol"], d:0.03, unit:"mg", mv:"40 min", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Moexipril", syn:["Moexipril"], d:1, unit:"mg", mv:"12 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Morfina", syn:["Morfina","Dimorf"], d:0.4, unit:"mg", mv:"3 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona (0.4-2mg IV)", support:"Depressão respiratória é o maior risco.", ref:"AACT/EAPCCT" },
      { n:"Moxifloxacino", syn:["Moxifloxacino"], d:25, unit:"mg", mv:"12 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Moxonidina", syn:["Moxonidina"], d:0.02, unit:"mg", mv:"3 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Nabumetona", syn:["Nabumetona"], d:70, unit:"mg", mv:"27 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Nadolol", syn:["Nadolol"], d:11, unit:"mg", mv:"24 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Nafazolina", syn:["Nafazolina","Neosoro"], d:0.1, unit:"mg", mv:"Update", ca:"Sim (< 1h)", lg:"Não", support:"Bradicardia e depressão SNC em crianças.", ref:"AACT/EAPCCT" },
      { n:"Naproxeno", syn:["Naproxeno","Flanax"], d:35, unit:"mg", mv:"17 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Nebivolol", syn:["Nebivolol"], d:0.3, unit:"mg", mv:"50 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Nicardipina", syn:["Nicardipina"], d:3.5, unit:"mg", mv:"9 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Nifedipina", syn:["Nifedipina","Adalat"], d:1.2, unit:"mg", mv:"3.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Nimodipina", syn:["Nimodipina"], d:6, unit:"mg", mv:"10 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Nitrazepam", syn:["Nitrazepam"], d:0.4, unit:"mg", mv:"24 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Norfloxacino", syn:["Norfloxacino"], d:50, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Nortriptilina", syn:["Nortriptilina","Pamelor"], d:2.5, unit:"mg", mv:"26 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Ofloxacino", syn:["Ofloxacino"], d:25, unit:"mg", mv:"6 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Olmesartana", syn:["Olmesartana"], d:1.5, unit:"mg", mv:"15 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Olodaterol", syn:["Olodaterol"], d:0.35, unit:"mcg", mv:"22/45 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Oxazepam", syn:["Oxazepam"], d:3.5, unit:"mg", mv:"20 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Oxcarbazepina", syn:["Oxcarbazepina"], d:40, unit:"mg", mv:"9.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Oxicodona", syn:["Oxicodona","Oxycontin"], d:0.2, unit:"mg", mv:"3 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona (0.4-2mg IV)", ref:"AACT/EAPCCT" },
      { n:"Oximetazolina", syn:["Oximetazolina"], d:0.4, unit:"mg", mv:"8 dias", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Oxprenolol", syn:["Oxprenolol"], d:11, unit:"mg", mv:"2 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Paracetamol", syn:["Paracetamol","Acetaminofeno","Tylenol"], d:75, unit:"mg", mv:"3 hs", ca:"Sim (< 2h)", lg:"Não", ant:"N-Acetilcisteína (NAC)", ref:"Rumack-Matthew Nomogram; IBCC/EmCrit" },
      { n:"Paroxetina", syn:["Paroxetina"], d:3, unit:"mg", mv:"21 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Pentazocina", syn:["Pentazocina"], d:2.5, unit:"mg", mv:"3 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona", ref:"AACT/EAPCCT" },
      { n:"Perfenazina", syn:["Perfenazina"], d:0.6, unit:"mg", mv:"12 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Periciazina", syn:["Periciazina"], d:1, unit:"mg", mv:"Update", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Perindopril", syn:["Perindopril"], d:0.3, unit:"mg", mv:"17 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Petidina", syn:["Petidina","Meperidina"], d:6, unit:"mg", mv:"48 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona (Cuidado: risco de convulsão)", ref:"AACT/EAPCCT" },
      { n:"Pimozida", syn:["Pimozida"], d:0.5, unit:"mg", mv:"55 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Pindolol", syn:["Pindolol"], d:1, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Pipotiazina", syn:["Pipotiazina"], d:0.2, unit:"mg", mv:"Update", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Piroxicam", syn:["Piroxicam"], d:1, unit:"mg", mv:"50 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Pomalidomida", syn:["Pomalidomida"], d:0.2, unit:"mg", mv:"9.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Prazepam", syn:["Prazepam"], d:2, unit:"mg", mv:"70 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Primidona", syn:["Primidona"], d:60, unit:"mg", mv:"5 dias", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Proclorperazina", syn:["Proclorperazina"], d:2, unit:"mg", mv:"9 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Promazina", syn:["Promazina"], d:12, unit:"mg", mv:"40 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Prometazina", syn:["Prometazina","Fenergan"], d:3.5, unit:"mg", mv:"14 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Propranolol", syn:["Propranolol"], d:4.5, unit:"mg", mv:"6 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Quetiapina", syn:["Quetiapina"], d:15, unit:"mg", mv:"22 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Quinapril", syn:["Quinapril"], d:1, unit:"mg", mv:"3 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Ramipril", syn:["Ramipril"], d:3.2, unit:"mg", mv:"17 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Reboxetina", syn:["Reboxetina"], d:0.5, unit:"mg", mv:"Update", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Risperidona", syn:["Risperidona"], d:1, unit:"mg", mv:"24 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Ritalina", syn:["Ritalina","Metilfenidato"], d:1, unit:"mg", mv:"2 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Salbutamol", syn:["Salbutamol","Aerolin"], d:0.5, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Salmeterol", syn:["Salmeterol"], d:7, unit:"mcg", mv:"5.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Secobarbital", syn:["Secobarbital"], d:4, unit:"mg", mv:"40 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Sertralina", syn:["Sertralina"], d:7, unit:"mg", mv:"26 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Sibutramina", syn:["Sibutramina"], d:50, unit:"mg", mv:"Update", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Sildenafil", syn:["Sildenafil","Viagra"], d:3, unit:"mg", mv:"5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Sotalol", syn:["Sotalol"], d:7, unit:"mg", mv:"20 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Sulindaco", syn:["Sulindaco"], d:30, unit:"mg", mv:"17 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Tadalafil", syn:["Tadalafil","Cialis"], d:1, unit:"mg", mv:"17 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Talidomida", syn:["Talidomida"], d:7, unit:"mg", mv:"7.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Tapentadol", syn:["Tapentadol"], d:2, unit:"mg", mv:"4 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona", ref:"AACT/EAPCCT" },
      { n:"Telitromicina", syn:["Telitromicina"], d:100, unit:"mg", mv:"3 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Telmisartana", syn:["Telmisartana"], d:3, unit:"mg", mv:"24 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Temazepam", syn:["Temazepam"], d:1.5, unit:"mg", mv:"11 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Tenoxicam", syn:["Tenoxicam"], d:1.5, unit:"mg", mv:"81 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Terbutalina", syn:["Terbutalina"], d:1, unit:"mg", mv:"3.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Timolol", syn:["Timolol"], d:1, unit:"mg", mv:"5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Tioridazina", syn:["Tioridazina"], d:6, unit:"mg", mv:"10 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Tolbutamida", syn:["Tolbutamida"], d:30, unit:"mg", mv:"8 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Tolmetino", syn:["Tolmetino"], d:85, unit:"mg", mv:"5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Topiramato", syn:["Topiramato"], d:10, unit:"mg", mv:"21 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Torasemida", syn:["Torasemida"], d:0.4, unit:"mg", mv:"6 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Tramadol", syn:["Tramadol"], d:4, unit:"mg", mv:"9 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Naloxona (0.4-2mg IV)", support:"Risco de convulsão. Cuidado com naloxona.", ref:"AACT/EAPCCT" },
      { n:"Triamterene", syn:["Triamterene"], d:15, unit:"mg", mv:"2 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Triazolam", syn:["Triazolam"], d:0.02, unit:"mg", mv:"5.5 hs", ca:"Sim (< 1h)", lg:"Não", ant:"Flumazenil", ref:"AACT/EAPCCT" },
      { n:"Trifluoperazina", syn:["Trifluoperazina"], d:0.4, unit:"mg", mv:"22 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Trimipramina", syn:["Trimipramina"], d:5, unit:"mg", mv:"23 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Tripelenamina", syn:["Tripelenamina"], d:5, unit:"mg", mv:"5.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Triprolidina", syn:["Triprolidina"], d:1, unit:"mg", mv:"5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Valaciclovir", syn:["Valaciclovir"], d:200, unit:"mg", mv:"3 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Valsartana", syn:["Valsartana"], d:5, unit:"mg", mv:"9 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Vardenafil", syn:["Vardenafil"], d:0.5, unit:"mg", mv:"6 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Venlafaxina", syn:["Venlafaxina"], d:7, unit:"mg", mv:"15 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Verapamil", syn:["Verapamil"], d:5, unit:"mg", mv:"8 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Vilanterol", syn:["Vilanterol"], d:1.5, unit:"mcg", mv:"11 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Xilometazolina", syn:["Xilometazolina","Neosoro"], d:0.4, unit:"mg", mv:"Update", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Xipamida", syn:["Xipamida"], d:3, unit:"mg", mv:"8 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
      { n:"Zofenopril", syn:["Zofenopril"], d:2, unit:"mg", mv:"5.5 hs", ca:"Sim (< 1h)", lg:"Não", ref:"AACT/EAPCCT" },
    ];
