window.database = [
  // --- Canônicos com seus antídotos/suporte ---
  { n: "AAS", syn: ["Ácido acetilsalicílico"], d: 100, unit: "mg", mv: "30 hs", ant: "Bicarbonato de Sódio", support: "Alcalinização urinária." },
  { n: "Amitriptilina", d: 3, unit: "mg", mv: "25 hs", ant: "Bicarbonato de Sódio", support: "ECG (QRS). Tratar convulsões." },
  { n: "Atenolol", d: 5, unit: "mg", mv: "7 hs", ant: "Glucagon / Insulina", support: "Monitorar hemodinâmica." },
  { n: "Carbamazepina", d: 20, unit: "mg", mv: "20 hs", support: "Carvão seriado (MDAC)." },
  { n: "Clonazepam", d: 0.6, unit: "mg", mv: "40 hs", ant: "Flumazenil (Cuidado)", support: "Suporte respiratório." },
  { n: "Diazepam", d: 0.7, unit: "mg", mv: "48 hs", ant: "Flumazenil (Cuidado)", support: "Suporte ventilatório." },
  { n: "Digoxina", d: 20, unit: "mcg", mv: "40 hs", ant: "Fab Anti-Digoxina", support: "Monitorar K+ e ECG." },
  { n: "Fenobarbital", d: 4, unit: "mg", mv: "5 dias", support: "Alcalinização urinária." },
  { n: "Lítio", syn: ["Litio", "Carbonato Lítio", "Lítio (Carbonato)", "Carbonato de lítio"], d: 50, unit: "mg", mv: "24 hs", noCharcoal: true, ant: "Hemodiálise", support: "Hidratação. Carvão ineficaz." },
  { n: "Paracetamol", d: 75, unit: "mg", mv: "3 hs", ant: "N-Acetilcisteína", support: "Nomograma em 4h." },

  // --- Base (itens comuns já usados no app/trecho do PDF), com sinônimos quando útil ---
  { n: "Aciclovir", d: 300, unit: "mg", mv: "3 hs" },
  { n: "Ácido Valpróico", syn: ["Valproato", "Ácido valpróico"], d: 200, unit: "mg", mv: "20 hs" },
  { n: "Alprazolam", d: 0.05, unit: "mg", mv: "15 hs" },
  { n: "Amlodipina", d: 0.2, unit: "mg", mv: "50 hs" },
  { n: "Amoxicilina", d: 250, unit: "mg", mv: "1,5 hs" },
  { n: "Haloperidol", syn: ["Haldol"], d: 0.5, unit: "mg", mv: "35 hs" },
  { n: "Hidroclorotiazida", d: 3.5, unit: "mg", mv: "15 hs" },
  { n: "Ibuprofeno", d: 100, unit: "mg", mv: "2,5 hs" },
  { n: "Levotiroxina", syn: ["T4", "L-tiroxina"], d: 20, unit: "mcg", mv: "7 dias" },
  { n: "Losartana", d: 3.5, unit: "mg", mv: "9 hs" },
  { n: "Metformina", d: 80, unit: "mg", mv: "6,5 hs" },
  { n: "Metoprolol", d: 10, unit: "mg", mv: "3,5 hs" },
  { n: "Midazolam", d: 1.0, unit: "mg", mv: "2,5 hs" },
  { n: "Morfina", d: 0.4, unit: "mg", mv: "3 hs" },
  { n: "Naproxeno", d: 35, unit: "mg", mv: "17 hs" },
  { n: "Nifedipina/R", d: 1.2, unit: "mg", mv: "3,5/11 hs" },
  { n: "Paroxetina", d: 3, unit: "mg", mv: "21 hs" },
  { n: "Sertralina", d: 7, unit: "mg", mv: "26 hs" },
  { n: "Tadalafila", syn: ["Tadalafil"], d: 1, unit: "mg", mv: "17 hs" },
  { n: "Valsartana", d: 5, unit: "mg", mv: "6 hs" },
  { n: "Venlafaxina", d: 5, unit: "mg", mv: "15 hs" },
  { n: "Verapamil", d: 10, unit: "mg", mv: "12 hs" },
  { n: "Zolpidem", d: 0.5, unit: "mg", mv: "2,5 hs" },
  { n: "Aceclofenaco", d: 15, unit: "mg", mv: "" },
  { n: "Acemetacina", d: 8.5, unit: "mg", mv: "11 hs" },
  { n: "Ácido Nalidíxico", d: 150, unit: "mg", mv: "7 hs" },
  { n: "Ácido Tiaprofênico", d: 40, unit: "mg", mv: "2 hs" },
  { n: "Amilorida", d: 1.5, unit: "mg", mv: "9 hs" },
  { n: "Amobarbital", d: 4, unit: "mg", mv: "25 hs" },
  { n: "Avanafil", d: 6, unit: "mg", mv: "17 hs" },
  { n: "Azapropazona", d: 50, unit: "mg", mv: "14 hs" },
  { n: "Azilsartana", d: 5, unit: "mg", mv: "11 hs" },
  { n: "Bambuterol", d: 1.5, unit: "mg", mv: "21 hs" },
  { n: "Barbital", d: 20, unit: "mg", mv: "48 hs" },
  { n: "Benazepril", d: 0.5, unit: "mg", mv: "22 hs" },
  { n: "Bendroflumetiazida", d: 0.4, unit: "mg", mv: "8,5 hs" },
  { n: "Betaxolol", d: 1, unit: "mg", mv: "22 hs" },
  { n: "Bisoprolol", d: 0.7, unit: "mg", mv: "12 hs" },
  { n: "Bromazepam", d: 0.7, unit: "mg", mv: "20 hs" },
  { n: "Bronfenaco", d: 10, unit: "mg", mv: "4 hs" },
  { n: "Bronfeniramina", d: 3.5, unit: "mg", mv: "25 hs" },
  { n: "Bumetanida", d: 0.1, unit: "mg", mv: "3 hs" },
  { n: "Buprenorfina", d: 0.01, unit: "mg", mv: "7 hs" },
  { n: "Butobarbital", d: 6, unit: "mg", mv: "42 hs" },
  { n: "Candesartana", d: 0.6, unit: "mg", mv: "9 hs" },
  { n: "Captopril", d: 3.5, unit: "mg", mv: "2 hs" },
  { n: "Carprofeno", d: 20, unit: "mg", mv: "27 hs" },
  { n: "Carvedilol", d: 2.5, unit: "mg", mv: "6 hs" },
  { n: "Carteolol", d: 0.7, unit: "mg", mv: "12 hs" },
  { n: "Celiprolol", d: 14, unit: "mg", mv: "6 hs" },
  { n: "Cetobemidona", d: 0.4, unit: "mg", mv: "2,5 hs" },
  { n: "Cetoprofeno", d: 10, unit: "mg", mv: "4 hs" },
  { n: "Ciclobarbital", d: 8, unit: "mg", mv: "12 hs" },
  { n: "Ciclizina", d: 25, unit: "mg", mv: "10 hs" },
  { n: "Cilazapril", d: 0.2, unit: "mg", mv: "9 hs" },
  { n: "Cinarizina", d: 12, unit: "mg", mv: "6 hs" },
  { n: "Ciprofloxacino", d: 70, unit: "mg", mv: "5 hs" },
  { n: "Ciproheptadina", d: 2, unit: "mg", mv: "9 hs" },
  { n: "Claritromicina", d: 70, unit: "mg", mv: "5 hs" },
  { n: "Clemastina", d: 0.3, unit: "mg", mv: "21 hs" },
  { n: "Cliclobenzaprina", d: 1.5, unit: "mg", mv: "32 hs" },
  { n: "Clobazam", d: 1.5, unit: "mg", mv: "79 hs" },
  { n: "Clomipramina", d: 4, unit: "mg", mv: "36 hs" },
  { n: "Clopamida", d: 1.4, unit: "mg", mv: "10 hs" },
  { n: "Clordiazepoxido", d: 2, unit: "mg", mv: "78 hs" },
  { n: "Clorfeniramina", d: 0.85, unit: "mg", mv: "43 hs" },
  { n: "Clorpromazina", d: 6, unit: "mg", mv: "40 hs" },
  { n: "Clorprotixeno", d: 6, unit: "mg", mv: "12 hs" },
  { n: "Clortalidona", d: 3.5, unit: "mg", mv: "50 hs" },
  { n: "Clozapina", d: 10, unit: "mg", mv: "12 hs" }
  { n: "Dapoxetina", d: 4, unit: "mg", mv: "19 hs" },
  { n: "Dapsona", d: 5, unit: "mg", mv: "30 hs" },
  { n: "Desipramina", d: 3, unit: "mg", mv: "27 hs" },
  { n: "Desvenlafaxina", d: 3, unit: "mg", mv: "15 hs" },
  { n: "Dexibuprofeno", d: 60, unit: "mg", mv: "3,5 hs" },
  { n: "Dexcetoprofeno", d: 5, unit: "mg", mv: "4 hs" },
  { n: "Dihidrocodeína", syn: ["Dihidrocodeina"], d: 0.4, unit: "mg", mv: "3,5 hs" },
  { n: "Diflunisal", d: 50, unit: "mg", mv: "12 hs" },
  { n: "Dipipanona", d: 1.5, unit: "mg", mv: "3,5 hs" },
  { n: "Disopiramida", d: 15, unit: "mg", mv: "11 hs" },
  { n: "Doxilamina", d: 5, unit: "mg", mv: "10 hs" },
  { n: "Eplerenona", d: 7, unit: "mg", mv: "5 hs" },
  { n: "Eprosartana", d: 40, unit: "mg", mv: "9 hs" },
  { n: "Eritromicina", d: 70, unit: "mg", mv: "2 hs" },
  { n: "Espironolactona", d: 10, unit: "mg", mv: "11,5 hs" },
  { n: "Estazolam", d: 0.2, unit: "mg", mv: "24 hs" },
  { n: "Etizolam", d: 0.1, unit: "mg", mv: "8 hs" },
  { n: "Etodolaco", d: 30, unit: "mg", mv: "7 hs" },
  { n: "Famciclovir", d: 50, unit: "mg", mv: "2 hs" },
  { n: "Felodipina", d: 0.2, unit: "mg", mv: "25 hs" },
  { n: "Fenbufeno", d: 40, unit: "mg", mv: "17 hs" },
  { n: "Fenilefrina", d: 1, unit: "mg", mv: "3 hs" },
  { n: "Feniramina", d: 3.5, unit: "mg", mv: "19 hs" },
  { n: "Fenitoína", syn: ["Fenitoina"], d: 20, unit: "mg", mv: "230 hs" },
  { n: "Fenoprofeno", d: 85, unit: "mg", mv: "3 hs" },
  { n: "Fentanil", d: 0.04, unit: "mg", mv: "8 hs" },
  { n: "Flunitrazepam", d: 0.05, unit: "mg", mv: "35 hs" },
  { n: "Flurbiprofeno", d: 85, unit: "mg", mv: "6 hs" },
  { n: "Fluvoxamina", d: 15, unit: "mg", mv: "22 hs" },
  { n: "Formoterol", d: 1.5, unit: "mcg", mv: "10 hs" },
  { n: "Fosinopril", d: 1, unit: "mg", mv: "11,5 hs" },
  { n: "Gliclazida/R", d: 1.3, unit: "mg", mv: "12/20 hs" },
  { n: "Glipizida", d: 0.2, unit: "mg", mv: "4 hs" },
  { n: "Guanfacina", d: 0.15, unit: "mg", mv: "18 hs" },
  { n: "Hidromorfona", d: 0.1, unit: "mg", mv: "2,5 hs" },
  { n: "Hidroxizina", syn: ["Hidroxizine"], d: 10, unit: "mg", mv: "20 hs" },
  { n: "Imepitoin", d: 30, unit: "mg", mv: "20 hs" },
  { n: "Imidapril", d: 0.7, unit: "mg", mv: "24 hs" },
  { n: "Imipramina", d: 4, unit: "mg", mv: "19 hs" },
  { n: "Indacaterol", d: 10, unit: "mcg", mv: "5 dias" },
  { n: "Indapamida", d: 0.4, unit: "mg", mv: "24 hs" },
  { n: "Indometacina", d: 7, unit: "mg", mv: "11 hs" },
  { n: "Irbesartana", d: 10, unit: "mg", mv: "15 hs" },
  { n: "Lacidipina", d: 0.15, unit: "mg", mv: "19 hs" },
  { n: "Lenalidomida", d: 0.7, unit: "mg", mv: "5 hs" },
  { n: "Lercanidipina", d: 0.4, unit: "mg", mv: "10 hs" },
  { n: "Levobunolol", d: 1, unit: "mg", mv: "7 hs" },
  { n: "Levofloxacino", d: 35, unit: "mg", mv: "8 hs" },
  { n: "Levomepromazina", d: 6, unit: "mg", mv: "78 hs" },
  { n: "Lisinopril", d: 0.7, unit: "mg", mv: "12,5 hs" },
  { n: "Lofepramina", d: 4.5, unit: "mg", mv: "24 hs" },
  { n: "Loprazolam", d: 0.07, unit: "mg", mv: "14 hs" },
  { n: "Lormetazepam", d: 0.07, unit: "mg", mv: "11 hs" },
  { n: "Lornoxicam", d: 0.8, unit: "mg", mv: "4 hs" },
  { n: "Maprotilina", d: 3, unit: "mg", mv: "90 hs" },
  { n: "Meclozina", d: 5, unit: "mg", mv: "6 hs" },
  { n: "Meloxicam", d: 1, unit: "mg", mv: "20 hs" },
  { n: "Meptazinol", d: 8.5, unit: "mg", mv: "4 hs" },
  { n: "Metadona", d: 0.4, unit: "mg", mv: "60 hs" },
  { n: "Metildopa", d: 15, unit: "mg", mv: "16 hs (?)" },
  { n: "Metilfenidato", syn: ["Ritalina"], d: 1, unit: "mg", mv: "2 hs" },
  { n: "Metolazona", d: 0.7, unit: "mg", mv: "10 hs" },
  { n: "Misoprostol", d: 0.03, unit: "mg", mv: "40 min" },
  { n: "Moexipril", d: 1, unit: "mg", mv: "12 hs" },
  { n: "Moxifloxacino", d: 25, unit: "mg", mv: "12 hs" },
  { n: "Moxonidina", d: 0.02, unit: "mg", mv: "3 hs" },
  { n: "Nabumetona", d: 70, unit: "mg", mv: "27 hs" },
  { n: "Nadolol", d: 11, unit: "mg", mv: "24 hs" },
  { n: "Nafazolina", d: 0.1, unit: "mg", mv: "* (?)" },
  { n: "Nebivolol", d: 0.3, unit: "mg", mv: "50 hs" },
  { n: "Nicardipina", d: 3.5, unit: "mg", mv: "9 hs" },
  { n: "Nimodipina", d: 6, unit: "mg", mv: "10 hs" },
  { n: "Nitrazepam", d: 0.4, unit: "mg", mv: "24 hs" },
  { n: "Norfloxacino", d: 50, unit: "mg", mv: "4 hs" },
  { n: "Nortriptilina", d: 2.5, unit: "mg", mv: "26 hs" },
  { n: "Ofloxacino", d: 25, unit: "mg", mv: "6 hs" },
  { n: "Olodaterol", d: 0.35, unit: "mcg", mv: "22/45 hs" },
  { n: "Oxazepam", d: 3.5, unit: "mg", mv: "20 hs" },
  { n: "Oxcarbazepina", d: 40, unit: "mg", mv: "9,5 hs" },
  { n: "Oxicodona", d: 0.2, unit: "mg", mv: "3 hs" },
  { n: "Oximetazolina", d: 0.4, unit: "mg", mv: "8 dias" },
  { n: "Oxprenolol", d: 11, unit: "mg", mv: "2 hs" }
  { n: "Pentazocina", d: 2.5, unit: "mg", mv: "3 hs" },
  { n: "Perfenazina", d: 0.6, unit: "mg", mv: "12 hs" },
  { n: "Periciazina", d: 1, unit: "mg", mv: "8 hs (?)" },
  { n: "Perindopril", d: 0.3, unit: "mg", mv: "17 hs" },
  { n: "Petidina", syn: ["Meperidina"], d: 6, unit: "mg", mv: "48 hs" },
  { n: "Pimozida", d: 0.5, unit: "mg", mv: "55 hs" },
  { n: "Ranitidina", d: 10, unit: "mg", mv: "3 hs" },
  { n: "Risperidona", d: 0.2, unit: "mg", mv: "24 hs" },
  { n: "Ritonavir", d: 20, unit: "mg", mv: "4 hs" },
  { n: "Rivastigmina", d: 0.2, unit: "mg", mv: "1,5 hs" },
  { n: "Sildenafila", syn: ["Sildenafil"], d: 3, unit: "mg", mv: "4 hs" },
  { n: "Sinvastatina", d: 2, unit: "mg", mv: "2 hs" },
  { n: "Sulfametoxazol", d: 200, unit: "mg", mv: "10 hs" },
  { n: "Sumatriptana", d: 3, unit: "mg", mv: "2,5 hs" },
  { n: "Teofilina", d: 10, unit: "mg", mv: "8 hs" },
  { n: "Tramadol", d: 5, unit: "mg", mv: "7 hs" },
  { n: "Trazodona", d: 10, unit: "mg", mv: "9 hs" },
  { n: "Tricíclicos", syn: ["Triciclicos"], d: 2.5, unit: "mg", mv: "?" },
  { n: "Trimetoprim", d: 20, unit: "mg", mv: "12 hs" },
  { n: "Valeriana", d: 30, unit: "mg", mv: "1 h" },
];
